/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aliaksandr.melas (https://sketchfab.com/alexandr.melas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starry-galaxy-sky-hdri-background-photosphere-e85426f6c246446a87c01e3f8357d98d
Title: Starry galaxy sky HDRi background photosphere
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import starsScene from "../assets/3d/stars.glb";

const Stars = ({ isRotating }) => {
  const stars = useGLTF(starsScene);
  const starsRef = useRef();
  useFrame((_, delta) => {
    if (isRotating) {
      starsRef.current.rotation.y += 0.15 * delta;
    }
  });
  return (
    <mesh ref={starsRef}>
      <primitive object={stars.scene} />
    </mesh>
  );
};

export default Stars;
